---
root: true
extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - no-not-accumulator-reassign
  - prettier
env:
  node: true
rules:
  no-not-accumulator-reassign/no-not-accumulator-reassign:
    [2, ['reduce'], { props: true }]
  no-underscore-dangle: off
  import/no-unresolved: ['error', { ignore: ['sketch'] }]
  import/extensions: ['error', { ignore: 'sketch' }]
globals:
  NSOKButton: 0
  NSSavePanel: 0
  NSString: 0
  NSUTF8StringEncoding: 0
